name: Issue Triggered Workflow  
  
on:  
  issues:  
    types: [opened, edited]  
  
jobs:  
  run-permission-template-script:  
    runs-on: ubuntu-latest  
    if: github.event.issue.pull_request == null # Ensure it's not a PR  
  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  
  
      - name: Extract issue body and parse inputs    
        id: get-inputs    
        run: |    
          ISSUE_BODY=$(jq -r .issue.body "$GITHUB_EVENT_PATH")    
          echo "Issue Body:"    
          echo "$ISSUE_BODY"    
          ASKID=$(echo "$ISSUE_BODY" | awk '/### AideID-AskID/{getline; getline; print}' | xargs)    
          ADMIN_GROUP=$(echo "$ISSUE_BODY" | awk '/### Admin_Group/{getline; getline; print}' | xargs)    
          DEV_GROUP=$(echo "$ISSUE_BODY" | awk '/### Dev_Group/{getline; getline; print}' | xargs)    
          PROJECTKEY=$(echo "$ISSUE_BODY" | awk '/### Projectkey/{getline; getline; print}' | xargs)    
          ISSUE_OPNER_MSID=$(jq -r .issue.user.login "$GITHUB_EVENT_PATH")  
            
          if [[ -z "$ASKID" || -z "$ADMIN_GROUP" || -z "$DEV_GROUP" || -z "$PROJECTKEY" ]]; then    
            echo "One or more extracted values are empty."    
            exit 1    
          fi    
            
          echo "ASKID=${ASKID}" >> $GITHUB_ENV    
          echo "ADMIN_GROUP=${ADMIN_GROUP}" >> $GITHUB_ENV    
          echo "DEV_GROUP=${DEV_GROUP}" >> $GITHUB_ENV    
          echo "PROJECTKEY=${PROJECTKEY}" >> $GITHUB_ENV  
          echo "ISSUE_OPNER_MSID=${ISSUE_OPNER_MSID}" >> $GITHUB_ENV  
  
      - name: Update issue  
        uses: actions-cool/issues-helper@v3  
        with:  
          actions: 'update-issue'  
          token: ${{ secrets.GITHUB_TOKEN }}  
          issue-number: ${{ github.event.issue.number }}  
          state: 'open'  
          title: 'AskID: ${{ env.ASKID }}'  
          
